modLoader="javafml"
loaderVersion="[40,)"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
updateJSONURL="${mod_update_url}"
version="${file.jarVersion}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
#logoFile="logo.png"
credits="${mod_author}"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
